### PR TITLE
Getting linux compiling (WIP)

### PR DESCRIPTION
**Pull request by IkerGalardi**
Getting the engine to compile (not link). Having this would be a major improvement and would let me test newer commits more easily. Linking the engine would be a bigger job as libraries should be compiled for linux (or use installed ones).

Some issues regarding portability that need to be addressed:

* `snprintf_s` and `strncmp_s` are not standard at all. Don't really know if the `_s` have any *special sauce* that make them super secure so it could be a good idea to use macros to select the standard or `_s` versions depending on the platform. Don't know if its really worth the pain.

### CODE REVIEW

**Comment by PanosK92** [comment]
Maybe a solution to the third-party dependencies could be [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by PanosK92** [comment]
Is [this](9d11456bb3da485b9f750d23511f98b0cb6b670e) necessery ?

Spartan.h, the precompiled header, already includes some core header files, couldn't we add any required header files there ?

The reasoning being to have everything in one place.

Thanks for the great work !

**Comment by IkerGalardi** [comment]
> Maybe a partial solution to the third-party dependencies issue could be [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

I've thought of that aswell, but that means that the libraries need to be compiled (by the project generation script maybe?). Ofcourse, not all libraries because SDL is included in most linux distributions; but other libraries like bullet or FSR2 are not (so those need to be built). 

Precompiling as on windows is not a good idea as glibc tends to break ABI too often and that would lead to working on some platforms only. Don't really know if that applies to static libraries (as they are basically a collection of object files, literally), but it seems that that should be a problem.

> Is [this](9d11456bb3da485b9f750d23511f98b0cb6b670e) necessery ?
> 
> Spartan.h, the precompiled header, already includes some core header files, couldn't we add any required header files there ?
> 
> The reasoning being to have everything in one place.
> 
> Thanks for the great work !

The thing is that precompiled headers can be included by simply doing `Spartan.h` on windows, even if that header file is not on the include path whereas in gcc/clang the path to the file needs to be provided (`Runtime/Core/Spartan.h`). Tryied to add the full path but then MSVC complains. The best solution seems to be to add `Runtime/Core` to the include path so that both platforms are happy (let me know if you know of a better solution).

Im finishing my computer science degree (my end of degree thesis is driving me crazy) and installing WSL2 (so i can be able to compile in both platforms without changing computers) so soon I will be able to start working on this again.

PD: thanks for fixing the windows build 😉

**Comment by PanosK92** [comment]
Since this is the case with "Runtime/Core" then that's fine. I added comment in the build script just we remember the reason.

Good luck with your thesis, I'm sure you'll do great since you understand all this so far. 
No worries, do what you and the engine will always be here 😄 

I'm merging this, thank you!

**Pull request merged**
