### PR TITLE
Some fixes for linking editor on linux

### PR DESCRIPTION
**Pull request by IkerGalardi**
This PR adds several changes in order to advance on the editor being linked and hopefully runable. The next are the main changes:

- Change to use system headers on the linux environment rather that using the repository included ones.
- Minor fixes with certain library instalations
- Disabling audio related code on linux installs
- Enable dynamic linking on linux

It is also important to note that the build environment's freeimage library is missing the `Utilities.h` header and it's functions, so maybe freeimage should be also compiled on the environment like Compressonator? 

In order to use the docker environment, first build the image by using the next command:
``` 
docker buildx build build_scripts/ -t spartanbuildenv
```
Then you can either enter the container and simply use the shell as normal or just run make on the container and exit:
``` 
docker run -v $(pwd):/code -w /code/ -it spartanbuildenv      # Enter the container on the repository folder
docker run -v $(pwd):/code -w /code/ -it spartanbuildenv make # Run make inside the container and exit out of the container 
```

#66

### CODE REVIEW

**Comment by IkerGalardi** [comment]
Hopefully the error is related with dynamic linking 🤞

This will be my last PR in some time. So for anyone that want's to follow this work I would recommend on fixing the FreeImage realted issues, and finish adding the last libraries to the environment. Linking errors should then be resolved and if there is no undefined behavior or linux vulkan driver specific issues the engine should run just fine.

**Comment by PanosK92** [comment]
Appreciate the work you do, no worries, leave this PR with me, I'll go through it soon

**Comment by PanosK92** [comment]
I'll have to do some work before merging this, linking should remain static for Windows

**Comment by IkerGalardi** [comment]
I've done the fixes.

I have a couple of free days so I'll put the PR in draft and try to get FreeImage issues solved.

**Comment by IkerGalardi** [comment]
I'll open it for review/merge. I'll do the follow up work when I have time!

**Comment by PanosK92** [comment]
Linking seems to work fine on Windows again, merging, thanks!

**Pull request merged**
