### PR TITLE
Implement undo system (WIP)

### PR DESCRIPTION
**Pull request by perkele1989**
This PR is still a work in progress and shouldn't be merged yet.

Implements the foundation for an undo system. Have tried to follow existing codebase style and idioms.

Needs to fix before merge:

1. Improve memory management on the undo/redo buffer, likely just change it to a preallocated array with a cursor to signify where in commit history we are.
2. Fix input issue regarding ImGuizmo (inconsistent results from manipulate function)
3. Implement and invoke initialize/shutdown functions, to clean up memory from the undo/redo stacks

### CODE REVIEW

**Comment by haikarainen** [comment]
The gist of it:

1. Spartan::CommandStack is our "singleton" class to manage the undo stack. It manages the undo/redo buffer, and exposes functions to Undo, Redo, and apply new commands.
2. To implement a new command, inherit from Spartan::Command, and override the OnApply and OnRevert functions appropriately (making sure to store any required states as member variables). Check out Spartan::TransformEntity for a simple example that transforms an entity.
3. Added obvious hotkeys in WorldViewer (where the other ones are)

Additional thing to consider: Right now we are using the object ID from the entity to track it. Ideally we likely want to track a more consistent ID / UUID / unique entity name, to support things like undo for entity creation/deletion, and scenarios where entities may load/unload in editor. Could track by weak_ptr or shared_ptr too but that wouldn't solve the aforementioned issue.

**Comment by PanosK92** [comment]
Simple, gets the job done, I like it. I'll talk to you in Discord about the IDs.

**Comment by NickPolyder** [comment]
Hello, 

Can I ask what is left to be done on this PR ? 

From what I can understand a basic MVP of the undo system is there. Why not trial it as is and let people come up with ideas on how to make it better or simply make other commands for their favourite features ?

Best,

**Comment by haikarainen** [comment]
> Hello,
> 
> Can I ask what is left to be done on this PR ?
> 
> From what I can understand a basic MVP of the undo system is there. Why not trial it as is and let people come up with ideas on how to make it better or simply make other commands for their favourite features ?
> 
> Best,

Hey,

sorry I’ve been swamped and haven’t been able to work much on this, but the idea is to get basic undo functionality going I guess before merging this. I’m working right now on implementing internal serialization to facilitate undoing object deletion and similar.

**Comment by NickPolyder** [comment]
Oh Cool. Yeah dont worry about the timing everybody have life to deal with. 

Keep up the good work. 

Best,

**Comment by PanosK92** [comment]
The foundation is there, once functionality of existing commands is glitch free (say transform gizmo manipulation), I can merge this, and we'll take it from there. Thanks!

**Comment by ApostolosBouz** [comment]
>  (say transform gizmo manipulation)
What's the issue with the transform gizmo again ?

**Pull request merged**
