### PR TITLE
[buildscripts]: support for freebsd os

### PR DESCRIPTION
**Pull request by Martinfx**
Hi,
I added support for FreeBSD os.

### CODE REVIEW

**Comment by Martinfx** [comment]
I still have problem with includes. I added bullet include but `Game/../Physics/BulletPhysicsHelper.h:28:10: fatal error: 'LinearMath/btQuaternion.h' file not found
   28 | #include "LinearMath/btQuaternion.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by PanosK92** [comment]
Supporting FreeBSD only makes sense if there's an existing FreeBSD build or active development toward one. Our current focus is on Windows and Linux (in progress). Therefore, I am closing this issue.

**Comment by Martinfx** [comment]
> Supporting FreeBSD only makes sense if there's an existing FreeBSD build or active development toward one. Our current focus is on Windows and Linux (in progress). Therefore, I am closing this issue.

Why close, I wanted help with support

**Comment by Martinfx** [comment]
> Because you didn't justify why FreeBSD supported is needed and didn't demonstrate how you can tackle the port, say doing Vulkan. I suggest you continue working on your project (OpenGL), learn a few things, and in the future, you can start a discussion on this topic.

Reason is easy. I use FreeBSD as the main OS (PC, laptop) and I like port applications on FreeBSD. I am also a maintainer of packages on FreeBSD.

**Comment by PanosK92** [comment]
That would be an answer to the question, why would you like to add FreeBSD support, not why will Spartan benefit from it. There are also a multiple technical factors that have to be solved when porting to another platform. Trust me, there is a big difference between modify the build script and sitting down to port an engine.

**Comment by kristiker** [comment]
That sounds like it will not benefit many users and will only add burden to the developers.

**Comment by Martinfx** [comment]
> That sounds like it will not benefit many users and will only add burden to the developers.

I am a developer and I would take care of the platform FreeBSD

**Pull request closed without merging**
