### PR TITLE
imgui style update

### PR DESCRIPTION
**Pull request by ege-del**
needs a little polish but i think its good time to get some feedback on the general idea and implementation

using static variables for now just to check things quickly, ideally most of the ImGui_Style.h code would be contained in its widget with theme editor window. but we would still need some static variables so each widget can refer to common colors for 'info' 'warning' 'error' etc
col4

### CODE REVIEW

**Comment by PanosK92** [comment]
I’ve had a look at your work, and I’m impressed! The theme is definitely a step up, and minimalism/simplicity is something I’m a big fan of. Feel free to add whatever static variables you need, keeping it simple is the way to go.

Proceed as you see fit, I think you’ve got this. Let me know when you want feedback or are ready to merge.

**Comment by ege-del** [comment]
ready to merge, let me know if you notice any problems

**Comment by PanosK92** [comment]
You did a fantastic job, thank you.

**Comment by PanosK92** [comment]
I reached out on Discord, please check.

**Pull request merged**
