### PR TITLE
Compile runtime on linux

### PR DESCRIPTION
**Pull request by IkerGalardi**
With this PR the runtime of the game engine gets compiled in linux.

The most important change is the "modification" of the SDL library configuration. IMO this is a hint on that the approach of including the library and headers falls apart when trying to port the engine into different platforms.

#66

### CODE REVIEW

**Comment by IkerGalardi** [comment]
The compilation error is generated because the wrong video driver is defined on the  windows build. Myabe doing a`undef` is not the best idea and instead a `define` should be used explicitly for each platform.

**Comment by PanosK92** [comment]
Thank you for trying to do this, I'll get back to you soon 😄

**Comment by PanosK92** [comment]
I took care of the issue. Can you please re-generate the project files and ensure that the runtime still compiles for Linux?

**Comment by IkerGalardi** [comment]
The path was case insensitive, causing the function to fail on linux (fixed on the latest commit.

Sorry for the wrong naming on the commits, is there any guide on what subsystem names to put?

**Comment by PanosK92** [comment]
Excellent, thanks!

**Pull request merged**
